sudo: required
services:
  - docker
before_install:
  - docker build -t crojasla/docker-react -f Dockerfile.development .
script:
  - docker run crojasla/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react-test "
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-us-west-1-239630721544"
  bucket_path: "docker-react-test "
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"